using MaxPayroll.SiteEvaluator.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MaxPayroll.SiteEvaluator.Services;

/// <summary>
/// Report generation service using QuestPDF.
/// </summary>
public class ReportService : IReportService
{
    private readonly ILogger<ReportService> _logger;

    public ReportService(ILogger<ReportService> logger)
    {
        _logger = logger;
        
        // Configure QuestPDF license
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public Task<byte[]> GenerateFullReportAsync(SiteEvaluation evaluation, ReportOptions options, CancellationToken ct = default)
    {
        _logger.LogInformation("Generating full report for evaluation {Id}", evaluation.Id);
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeHeader(c, evaluation, options));
                page.Content().Element(c => ComposeFullContent(c, evaluation, options));
                page.Footer().Element(ComposeFooter);
            });
        });

        var bytes = document.GeneratePdf();
        return Task.FromResult(bytes);
    }

    public Task<byte[]> GenerateSummaryReportAsync(SiteEvaluation evaluation, CancellationToken ct = default)
    {
        _logger.LogInformation("Generating summary report for evaluation {Id}", evaluation.Id);
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeHeader(c, evaluation, new ReportOptions()));
                page.Content().Element(c => ComposeSummaryContent(c, evaluation));
                page.Footer().Element(ComposeFooter);
            });
        });

        var bytes = document.GeneratePdf();
        return Task.FromResult(bytes);
    }

    public Task<byte[]> GenerateGeotechBriefAsync(SiteEvaluation evaluation, CancellationToken ct = default)
    {
        _logger.LogInformation("Generating geotech brief for evaluation {Id}", evaluation.Id);
        
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Element(c => ComposeHeader(c, evaluation, new ReportOptions()));
                page.Content().Element(c => ComposeGeotechContent(c, evaluation));
                page.Footer().Element(ComposeFooter);
            });
        });

        var bytes = document.GeneratePdf();
        return Task.FromResult(bytes);
    }

    public Task<byte[]> GenerateDueDiligencePackAsync(SiteEvaluation evaluation, CancellationToken ct = default)
    {
        _logger.LogInformation("Generating due diligence pack for evaluation {Id}", evaluation.Id);
        
        // Due diligence pack is essentially a full report with all sections
        return GenerateFullReportAsync(evaluation, new ReportOptions
        {
            IncludeAppendices = true,
            IncludeMaps = true
        }, ct);
    }

    // === Private composition methods ===

    private static void ComposeHeader(IContainer container, SiteEvaluation evaluation, ReportOptions options)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(col =>
            {
                col.Item().Text("SITE EVALUATION REPORT").Bold().FontSize(16);
                col.Item().Text(evaluation.Location.Address).FontSize(12);
                col.Item().Text($"Report Date: {DateTime.Now:d MMMM yyyy}").FontSize(9).FontColor(Colors.Grey.Medium);
            });

            if (!string.IsNullOrEmpty(options.CompanyName))
            {
                row.ConstantItem(100).AlignRight().Text(options.CompanyName).FontSize(9);
            }
        });
    }

    private static void ComposeFooter(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem().Text(text =>
            {
                text.Span("Generated by Max Site Evaluator | ");
                text.Span("Page ").FontSize(8);
                text.CurrentPageNumber().FontSize(8);
                text.Span(" of ").FontSize(8);
                text.TotalPages().FontSize(8);
            });
        });
    }

    private static void ComposeFullContent(IContainer container, SiteEvaluation evaluation, ReportOptions options)
    {
        container.Column(col =>
        {
            // Executive Summary
            col.Item().PaddingVertical(10).Element(c => ComposeExecutiveSummary(c, evaluation));

            // Site Location
            col.Item().PaddingVertical(10).Element(c => ComposeSiteLocation(c, evaluation));

            // Zoning
            if (evaluation.Zoning != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeZoningSection(c, evaluation.Zoning));
            }

            // Hazards
            if (evaluation.Hazards != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeHazardsSection(c, evaluation.Hazards));
            }

            // Geotechnical
            if (evaluation.Geotech != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeGeotechSection(c, evaluation.Geotech));
            }

            // Infrastructure
            if (evaluation.Infrastructure != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeInfrastructureSection(c, evaluation.Infrastructure));
            }

            // Climate
            if (evaluation.Climate != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeClimateSection(c, evaluation.Climate));
            }

            // Data Gaps
            if (evaluation.DataGaps.Count > 0)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeDataGapsSection(c, evaluation.DataGaps));
            }
        });
    }

    private static void ComposeSummaryContent(IContainer container, SiteEvaluation evaluation)
    {
        container.Column(col =>
        {
            col.Item().Element(c => ComposeExecutiveSummary(c, evaluation));
            col.Item().PaddingVertical(10).Element(c => ComposeSiteLocation(c, evaluation));
            
            // Key findings table
            col.Item().PaddingVertical(10).Text("KEY FINDINGS").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                table.Cell().Border(1).Padding(5).Text("Zone").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Zoning?.Zone ?? "Not available");

                table.Cell().Border(1).Padding(5).Text("Liquefaction").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Hazards?.Liquefaction?.Category ?? "Not available");

                table.Cell().Border(1).Padding(5).Text("Flood Zone").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Hazards?.Flooding?.Zone ?? "Not available");

                table.Cell().Border(1).Padding(5).Text("Wind Zone").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Climate?.WindZone ?? "Not available");

                table.Cell().Border(1).Padding(5).Text("Water Supply").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Infrastructure?.Water?.Available == true ? "Available" : "Unknown");

                table.Cell().Border(1).Padding(5).Text("Wastewater").Bold();
                table.Cell().Border(1).Padding(5).Text(evaluation.Infrastructure?.Wastewater?.Available == true ? "Available" : "Unknown");
            });
        });
    }

    private static void ComposeGeotechContent(IContainer container, SiteEvaluation evaluation)
    {
        container.Column(col =>
        {
            col.Item().Text("GEOTECHNICAL BRIEF").Bold().FontSize(14);
            col.Item().PaddingVertical(5).Text(evaluation.Location.Address).FontSize(11);

            if (evaluation.Geotech != null)
            {
                col.Item().PaddingVertical(10).Element(c => ComposeGeotechSection(c, evaluation.Geotech));
            }
            else
            {
                col.Item().PaddingVertical(10).Text("No geotechnical data available for this location.");
            }

            if (evaluation.Hazards?.Liquefaction != null)
            {
                col.Item().PaddingVertical(10).Text("LIQUEFACTION STATUS").Bold().FontSize(12);
                col.Item().Text($"Category: {evaluation.Hazards.Liquefaction.Category}");
                col.Item().Text($"Description: {evaluation.Hazards.Liquefaction.Description}");
                if (evaluation.Hazards.Liquefaction.RequiresGeotechAssessment)
                {
                    col.Item().PaddingTop(5).Text("? Geotechnical assessment required").Bold().FontColor(Colors.Orange.Medium);
                }
            }
        });
    }

    private static void ComposeExecutiveSummary(IContainer container, SiteEvaluation evaluation)
    {
        container.Column(col =>
        {
            col.Item().Text("EXECUTIVE SUMMARY").Bold().FontSize(12);
            col.Item().PaddingVertical(5).Text($"Data Completeness: {evaluation.Completeness.CompletionPercentage:F0}%");
            col.Item().Text($"Status: {evaluation.Status}");
            
            if (evaluation.Warnings.Count > 0)
            {
                col.Item().PaddingTop(5).Text("Warnings:").Bold();
                foreach (var warning in evaluation.Warnings)
                {
                    col.Item().Text($"• {warning}").FontColor(Colors.Orange.Medium);
                }
            }
        });
    }

    private static void ComposeSiteLocation(IContainer container, SiteEvaluation evaluation)
    {
        container.Column(col =>
        {
            col.Item().Text("SITE LOCATION").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                AddTableRow(table, "Address", evaluation.Location.Address);
                AddTableRow(table, "Legal Description", evaluation.Location.LegalDescription);
                AddTableRow(table, "Title Reference", evaluation.Location.TitleReference ?? "Not available");
                AddTableRow(table, "Coordinates", $"{evaluation.Location.Latitude:F6}, {evaluation.Location.Longitude:F6}");
                AddTableRow(table, "Territorial Authority", evaluation.Location.TerritorialAuthority ?? "Not available");
            });
        });
    }

    private static void ComposeZoningSection(IContainer container, ZoningData zoning)
    {
        container.Column(col =>
        {
            col.Item().Text("ZONING & PLANNING").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                AddTableRow(table, "Zone", zoning.Zone);
                AddTableRow(table, "Zone Code", zoning.ZoneCode);
                AddTableRow(table, "Max Height", zoning.MaxHeight.HasValue ? $"{zoning.MaxHeight}m" : "Not specified");
                AddTableRow(table, "Max Coverage", zoning.MaxCoverage.HasValue ? $"{zoning.MaxCoverage}%" : "Not specified");
                AddTableRow(table, "District Plan", zoning.DistrictPlan);
            });

            if (zoning.Overlays.Count > 0)
            {
                col.Item().PaddingTop(5).Text("Overlays:").Bold();
                foreach (var overlay in zoning.Overlays)
                {
                    col.Item().Text($"• {overlay.Name}: {overlay.Description}");
                }
            }
        });
    }

    private static void ComposeHazardsSection(IContainer container, HazardData hazards)
    {
        container.Column(col =>
        {
            col.Item().Text("NATURAL HAZARDS").Bold().FontSize(12);

            if (hazards.Flooding != null)
            {
                col.Item().PaddingTop(5).Text("Flooding:").Bold();
                col.Item().Text($"Zone: {hazards.Flooding.Zone}");
                col.Item().Text($"Description: {hazards.Flooding.Description}");
            }

            if (hazards.Liquefaction != null)
            {
                col.Item().PaddingTop(5).Text("Liquefaction:").Bold();
                col.Item().Text($"Category: {hazards.Liquefaction.Category}");
                col.Item().Text($"Description: {hazards.Liquefaction.Description}");
            }

            if (hazards.Seismic != null)
            {
                col.Item().PaddingTop(5).Text("Seismic:").Bold();
                col.Item().Text($"Zone: {hazards.Seismic.Zone}");
                if (hazards.Seismic.NearbyFaults.Count > 0)
                {
                    col.Item().Text($"Nearby Faults: {hazards.Seismic.NearbyFaults.Count}");
                }
            }
        });
    }

    private static void ComposeGeotechSection(IContainer container, GeotechnicalData geotech)
    {
        container.Column(col =>
        {
            col.Item().Text("GEOTECHNICAL DATA").Bold().FontSize(12);
            col.Item().Text($"Site Class: {geotech.SiteClass ?? "Not determined"}");
            col.Item().Text($"Nearby Boreholes: {geotech.NearbyBoreholes.Count}");
            col.Item().Text($"Nearby CPTs: {geotech.NearbyCpts.Count}");
            col.Item().Text($"Nearby Reports: {geotech.NearbyReports.Count}");

            if (geotech.GeotechInvestigationRequired)
            {
                col.Item().PaddingTop(5).Text("? Site-specific geotechnical investigation recommended")
                    .Bold().FontColor(Colors.Orange.Medium);
            }
        });
    }

    private static void ComposeInfrastructureSection(IContainer container, InfrastructureData infrastructure)
    {
        container.Column(col =>
        {
            col.Item().Text("INFRASTRUCTURE").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                AddTableRow(table, "Water Supply", infrastructure.Water?.Available == true ? "Available" : "Not available");
                AddTableRow(table, "Wastewater", infrastructure.Wastewater?.Available == true ? "Available" : "Not available");
                AddTableRow(table, "Stormwater", infrastructure.Stormwater?.Available == true ? "Available" : "Not available");
                AddTableRow(table, "Power", infrastructure.Power?.Available == true ? "Available" : "Not available");
                AddTableRow(table, "Fibre", infrastructure.Communications?.FibreAvailable == true ? "Available" : "Not available");
                AddTableRow(table, "Gas", infrastructure.Gas?.Available == true ? "Available" : "Not available");
            });
        });
    }

    private static void ComposeClimateSection(IContainer container, ClimateData climate)
    {
        container.Column(col =>
        {
            col.Item().Text("CLIMATE DATA").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                });

                AddTableRow(table, "Wind Zone", climate.WindZone ?? "Not available");
                AddTableRow(table, "Climate Zone", climate.ClimateZone ?? "Not available");
                if (climate.Rainfall != null)
                {
                    AddTableRow(table, "Annual Rainfall", climate.Rainfall.AnnualMean.HasValue ? $"{climate.Rainfall.AnnualMean}mm" : "Not available");
                }
            });
        });
    }

    private static void ComposeDataGapsSection(IContainer container, List<DataGap> gaps)
    {
        container.Column(col =>
        {
            col.Item().Text("DATA GAPS").Bold().FontSize(12);
            col.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(1);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(1);
                });

                // Header
                table.Cell().Border(1).Padding(5).Text("Section").Bold();
                table.Cell().Border(1).Padding(5).Text("Field").Bold();
                table.Cell().Border(1).Padding(5).Text("Reason").Bold();
                table.Cell().Border(1).Padding(5).Text("Severity").Bold();

                foreach (var gap in gaps)
                {
                    table.Cell().Border(1).Padding(5).Text(gap.Section);
                    table.Cell().Border(1).Padding(5).Text(gap.Field);
                    table.Cell().Border(1).Padding(5).Text(gap.Reason);
                    table.Cell().Border(1).Padding(5).Text(gap.Severity.ToString());
                }
            });
        });
    }

    private static void AddTableRow(TableDescriptor table, string label, string value)
    {
        table.Cell().Border(1).Padding(5).Text(label).Bold();
        table.Cell().Border(1).Padding(5).Text(value);
    }
}
